### ISSUE TITLE
Doesnt work on toaster

### ISSUE THREAD

**Issue by angxlwtf** [XtraCube/AllOfUsBot#6]
![image](https://user-images.githubusercontent.com/75510960/107402513-0b49e280-6ad2-11eb-9ac7-bf3b60914145.png)
 this is my toaster model but it wont work, the thing doesnt load

**Comment by imaginehavingnogithubaccount** [comment]
Same thing happens to me
What toaster works?

**Comment by imaginehavingnogithubaccount** [comment]
don't delete my comment

**Comment by liammross** [comment]
I said no

**Comment by XtraCube** [comment]
Please stop GitHub is for serious matters, not joking about a plugin not working on a toaster

**Comment by liammross** [comment]
ok
